// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shorter.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	shorter.proto

It has these top-level messages:
	GetRequest
	PostRequest
	ServiceResponse
	ResponseData
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type PostRequest struct {
	Domain string `protobuf:"bytes,1,opt,name=domain" json:"domain,omitempty"`
}

func (m *PostRequest) Reset()                    { *m = PostRequest{} }
func (m *PostRequest) String() string            { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()               {}
func (*PostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PostRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type ServiceResponse struct {
	Err  string        `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Data *ResponseData `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *ServiceResponse) Reset()                    { *m = ServiceResponse{} }
func (m *ServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceResponse) ProtoMessage()               {}
func (*ServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *ServiceResponse) GetData() *ResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponseData struct {
	Url      string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Code     string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	ShortUri string `protobuf:"bytes,3,opt,name=short_uri,json=shortUri" json:"short_uri,omitempty"`
}

func (m *ResponseData) Reset()                    { *m = ResponseData{} }
func (m *ResponseData) String() string            { return proto.CompactTextString(m) }
func (*ResponseData) ProtoMessage()               {}
func (*ResponseData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResponseData) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ResponseData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResponseData) GetShortUri() string {
	if m != nil {
		return m.ShortUri
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*PostRequest)(nil), "pb.PostRequest")
	proto.RegisterType((*ServiceResponse)(nil), "pb.ServiceResponse")
	proto.RegisterType((*ResponseData)(nil), "pb.ResponseData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Shorter service

type ShorterClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
}

type shorterClient struct {
	cc *grpc.ClientConn
}

func NewShorterClient(cc *grpc.ClientConn) ShorterClient {
	return &shorterClient{cc}
}

func (c *shorterClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := grpc.Invoke(ctx, "/pb.Shorter/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shorterClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := grpc.Invoke(ctx, "/pb.Shorter/Post", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Shorter service

type ShorterServer interface {
	Get(context.Context, *GetRequest) (*ServiceResponse, error)
	Post(context.Context, *PostRequest) (*ServiceResponse, error)
}

func RegisterShorterServer(s *grpc.Server, srv ShorterServer) {
	s.RegisterService(&_Shorter_serviceDesc, srv)
}

func _Shorter_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Shorter/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorterServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shorter_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorterServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Shorter/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorterServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shorter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Shorter",
	HandlerType: (*ShorterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Shorter_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _Shorter_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shorter.proto",
}

func init() { proto.RegisterFile("shorter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0xdd, 0x3f, 0x54, 0x3b, 0x55, 0x5b, 0x46, 0x90, 0x45, 0x2f, 0x4b, 0x50, 0xe8, 0x41,
	0xf6, 0x50, 0x5f, 0x41, 0x28, 0xde, 0x34, 0xc5, 0xb3, 0x64, 0xbb, 0x83, 0x06, 0x6a, 0x13, 0x27,
	0x89, 0xcf, 0x2f, 0x89, 0xdb, 0x76, 0x11, 0x7a, 0xcb, 0xcc, 0xef, 0x63, 0x32, 0xdf, 0xc0, 0x85,
	0xfb, 0x34, 0xec, 0x89, 0x1b, 0xcb, 0xc6, 0x1b, 0xcc, 0x6d, 0x2b, 0x6a, 0x80, 0x25, 0x79, 0x49,
	0xdf, 0x81, 0x9c, 0x47, 0x84, 0x72, 0x6d, 0x3a, 0xaa, 0xb2, 0x3a, 0x9b, 0x8f, 0x65, 0x7a, 0x8b,
	0x7b, 0x98, 0xbc, 0x18, 0xb7, 0x47, 0xae, 0x61, 0xd4, 0x99, 0x2f, 0xa5, 0xb7, 0x3d, 0xd4, 0x57,
	0xe2, 0x19, 0xa6, 0x2b, 0xe2, 0x1f, 0xbd, 0x26, 0x49, 0xce, 0x9a, 0xad, 0x23, 0x9c, 0x41, 0x41,
	0xcc, 0x3d, 0x17, 0x9f, 0x78, 0x07, 0x65, 0xa7, 0xbc, 0xaa, 0xf2, 0x3a, 0x9b, 0x4f, 0x16, 0xb3,
	0xc6, 0xb6, 0xcd, 0x8e, 0x7e, 0x52, 0x5e, 0xc9, 0x94, 0x8a, 0x57, 0x38, 0x1f, 0x76, 0xe3, 0x9c,
	0xc0, 0x9b, 0xdd, 0x9c, 0xc0, 0x9b, 0xfd, 0x9e, 0xf9, 0x61, 0x4f, 0xbc, 0x85, 0x71, 0xd2, 0x7b,
	0x0f, 0xac, 0xab, 0x22, 0x05, 0x67, 0xa9, 0xf1, 0xc6, 0x7a, 0xf1, 0x01, 0xa7, 0xab, 0x3f, 0x77,
	0x7c, 0x80, 0x62, 0x49, 0x1e, 0x2f, 0xe3, 0xe7, 0x07, 0xf5, 0x9b, 0xab, 0x58, 0xff, 0x33, 0x10,
	0x27, 0xd8, 0x40, 0x19, 0xed, 0x71, 0x1a, 0xe3, 0xc1, 0x1d, 0x8e, 0xf0, 0xed, 0x28, 0x9d, 0xf6,
	0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x41, 0x72, 0x78, 0x2c, 0x6b, 0x01, 0x00, 0x00,
}
